export { validator } from './validators';

// Each validator is also exported on its own, straight from its file, so bundlers can tree-shake:
// `import { isEmail }` keeps isEmail and its dependencies only, while `validator` (the frozen
// registry) pulls every validator and locale table. Same functions: validator.isEmail === isEmail.
export { equals } from './validators/equals';
export { contains } from './validators/contains';
export { matches } from './validators/matches';
export { isEmail } from './validators/isEmail';
export { isURL } from './validators/isURL';
export { isMACAddress } from './validators/isMACAddress';
export { isIP } from './validators/isIP';
export { isIPRange } from './validators/isIPRange';
export { isFQDN } from './validators/isFQDN';
export { isBoolean } from './validators/isBoolean';
export { isIBAN, locales as ibanLocales } from './validators/isIBAN';
export { isBIC } from './validators/isBIC';
export { isAbaRouting } from './validators/isAbaRouting';
export { isAlpha, locales as isAlphaLocales } from './validators/isAlpha';
export { isAlphanumeric, locales as isAlphanumericLocales } from './validators/isAlphanumeric';
export { isNumeric } from './validators/isNumeric';
export { isPassportNumber, locales as passportNumberLocales } from './validators/isPassportNumber';
export { isPort } from './validators/isPort';
export { isLowercase } from './validators/isLowercase';
export { isUppercase } from './validators/isUppercase';
export { isAscii } from './validators/isAscii';
export { isFullWidth } from './validators/isFullWidth';
export { isHalfWidth } from './validators/isHalfWidth';
export { isVariableWidth } from './validators/isVariableWidth';
export { isMultibyte } from './validators/isMultibyte';
export { isSemVer } from './validators/isSemVer';
export { isSurrogatePair } from './validators/isSurrogatePair';
export { isInt } from './validators/isInt';
export { isIMEI } from './validators/isIMEI';
export { isFloat, locales as isFloatLocales } from './validators/isFloat';
export { isDecimal } from './validators/isDecimal';
export { isHexadecimal } from './validators/isHexadecimal';
export { isOctal } from './validators/isOctal';
export { isDivisibleBy } from './validators/isDivisibleBy';
export { isHexColor } from './validators/isHexColor';
export { isRgbColor } from './validators/isRgbColor';
export { isHSL } from './validators/isHSL';
export { isISRC } from './validators/isISRC';
export { isMD5 } from './validators/isMD5';
export { isHash } from './validators/isHash';
export { isJWT } from './validators/isJWT';
export { isJSON } from './validators/isJSON';
export { isEmpty } from './validators/isEmpty';
export { isLength } from './validators/isLength';
export { isLocale } from './validators/isLocale';
export { isByteLength } from './validators/isByteLength';
export { isULID } from './validators/isULID';
export { isUUID } from './validators/isUUID';
export { isMongoId } from './validators/isMongoId';
export { isAfter } from './validators/isAfter';
export { isBefore } from './validators/isBefore';
export { isIn } from './validators/isIn';
export { isLuhnNumber } from './validators/isLuhnNumber';
export { isCreditCard } from './validators/isCreditCard';
export { isIdentityCard } from './validators/isIdentityCard';
export { isEAN } from './validators/isEAN';
export { isISIN } from './validators/isISIN';
export { isISBN } from './validators/isISBN';
export { isISSN } from './validators/isISSN';
export { isMobilePhone, locales as isMobilePhoneLocales } from './validators/isMobilePhone';
export { isPostalCode, locales as isPostalCodeLocales } from './validators/isPostalCode';
export { isEthereumAddress } from './validators/isEthereumAddress';
export { isCurrency } from './validators/isCurrency';
export { isBtcAddress } from './validators/isBtcAddress';
export { isISO6346, isFreightContainerID } from './validators/isISO6346';
export { isISO6391 } from './validators/isISO6391';
export { isISO8601 } from './validators/isISO8601';
export { isISO15924 } from './validators/isISO15924';
export { isRFC3339 } from './validators/isRFC3339';
export { isISO31661Alpha2 } from './validators/isISO31661Alpha2';
export { isISO31661Alpha3 } from './validators/isISO31661Alpha3';
export { isISO31661Numeric } from './validators/isISO31661Numeric';
export { isISO4217 } from './validators/isISO4217';
export { isBase32 } from './validators/isBase32';
export { isBase58 } from './validators/isBase58';
export { isBase64 } from './validators/isBase64';
export { isDataURI } from './validators/isDataURI';
export { isMagnetURI } from './validators/isMagnetURI';
export { isMailtoURI } from './validators/isMailtoURI';
export { isMimeType } from './validators/isMimeType';
export { isLatLong } from './validators/isLatLong';
export { isWhitelisted } from './validators/isWhitelisted';
export { isSlug } from './validators/isSlug';
export { isStrongPassword } from './validators/isStrongPassword';
export { isDate } from './validators/isDate';
export { isTime } from './validators/isTime';
export { isLicensePlate } from './validators/isLicensePlate';
export { isVAT } from './validators/isVAT';

export * from './canBe';
export * from './convert';
export * as sanitizer from './sanitizer';
export { createValidator } from './createValidator';
export { scorePassword } from './validators/isStrongPassword';
export { ValidationConfigError } from './validators/util/errors';
// Every validator option / parameter type (IsEmailOptions, MobilePhoneLocale, …) and ValidatorRegistry.
export type * from './validators';
export type { NormalizeEmailOptions } from './sanitizer/normalizeEmail';
