#!/usr/bin/env node
// =============================================================================
// copy-wasm.js — Copy compiled WASM pkg files into dist/ after TypeScript build
//
// The compiled TS files have `require('#wasm')` / `import '#wasm'`.
// At runtime, package.json `imports` resolves #wasm to:
//   require  →  ./dist/wasm-node/archi_validation.js
//   import   →  ./dist/wasm-bundler/archi_validation.js
//
// This script copies the wasm-pack output to those locations.
// =============================================================================
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

const SOURCES = [
  { from: path.join(ROOT, 'src/wasm/pkg-node'), to: path.join(ROOT, 'dist/wasm-node') },
  { from: path.join(ROOT, 'src/wasm/pkg-bundler'), to: path.join(ROOT, 'dist/wasm-bundler') },
];

// Files generated by wasm-pack that we need at runtime
const WASM_FILES = ['archi_validation.js', 'archi_validation.d.ts', 'archi_validation_bg.wasm', 'archi_validation_bg.wasm.d.ts'];

let hasError = false;

for (const { from, to } of SOURCES) {
  if (!fs.existsSync(from)) {
    console.error(`[copy-wasm] ERROR: source directory not found: ${from}`);
    console.error(`[copy-wasm]        Run 'npm run build:wasm' first.`);
    hasError = true;
    continue;
  }

  fs.mkdirSync(to, { recursive: true });

  for (const file of WASM_FILES) {
    const src = path.join(from, file);
    const dst = path.join(to, file);
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dst);
      console.log(`[copy-wasm] copied ${path.relative(ROOT, src)} → ${path.relative(ROOT, dst)}`);
    }
  }
}

if (hasError) process.exit(1);

console.log('[copy-wasm] Done.');
